### ISSUE TITLE
free lancing

### ISSUE THREAD

**Issue by jaanavrt** [kshitijshah95/TechTM-website#1]
can i use this template is it opensource and rechange it?

and also
 website designer ? how much do u take for a template design my budget is 100$
for responive webbstie include site ui ux for mobile pc
very medium project not to complicated a clone of existing tempalte for a dating site template
thankls! do u have skype??

**Comment by kshitijshah95** [comment]
@jaanavrt You can find this free to use template on [HTML5Up](https://html5up.net/).
Yes, I am a website designer. I charge $200-$400 for a template based on the complexity. You can reach me at kshitijshah95@gmail.com.
